name: fedsim
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h497a2fe_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.108=mkl
  - blas-devel=3.9.0=8_mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - bottleneck=1.3.2=py38h5c078b8_3
  - brotlipy=0.7.0=py38h497a2fe_1001
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.10.26=h06a4308_2
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.1=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=11.0.3=h15472ef_8
  - cycler=0.10.0=py_2
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h9c3ff4c_0
  - faiss=1.7.0=py38cuda110h60a57df_5_cuda
  - faiss-gpu=1.7.0=h788eb59_5
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.0=h9c3ff4c_2
  - glib-tools=2.68.0=h9c3ff4c_2
  - google-auth=1.28.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.36.1=py38hdd6454d_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.1.0=nompi_py38hafa665b_100
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.10.0=py38h578d9bd_0
  - ipykernel=5.5.3=py38hd0cf306_0
  - ipython=7.23.0=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_ha53f305_0
  - libcurl=7.76.1=hc4aaa36_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libfaiss=1.7.0=cuda110h8045045_5_cuda
  - libfaiss-avx2=1.7.0=cuda110h1234567_5_cuda
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.68.0=h3e27bee_2
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_mkl
  - liblapacke=3.9.0=8_mkl
  - libllvm11=11.1.0=hf817b99_0
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - libprotobuf=3.15.6=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.41.0=h7f98852_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=11.1.0=h4bd325d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib=3.3.4=py38h578d9bd_0
  - matplotlib-base=3.3.4=py38h0efea84_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py38h497a2fe_1003
  - mkl=2020.4=h726a3e6_304
  - mkl-devel=2020.4=ha770c72_305
  - mkl-include=2020.4=h726a3e6_304
  - multidict=5.1.0=py38h497a2fe_1
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - ninja=1.10.2=h4bd325d_0
  - nltk=3.5=py_0
  - notebook=6.3.0=pyha770c72_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.63=hb5efdd6_0
  - numpy=1.20.2=py38h9894fe3_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1m=h7f8727e_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38ha9443f7_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - phe=1.4.0=py38h1cdfbd6_1
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=pyhd8ed1ab_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - prompt_toolkit=3.0.18=hd8ed1ab_0
  - protobuf=3.15.6=py38h709712a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-wget=3.2=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.0.3=py38h2035c66_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.0.3=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=he28a2e2_2
  - regex=2021.3.17=py38h497a2fe_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.2=py38h7b17777_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=pyh9f0ad1d_0
  - sortedcontainers=2.3.0=pyhd8ed1ab_0
  - sqlite=3.35.3=h74cdb3f_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - terminado=0.9.4=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yarl=1.6.3=py38h497a2fe_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - captum==0.3.1
    - deprecation==2.1.0
    - hiddenlayer==0.3
    - lesshash-bloomfilter==0.0.5
    - opencv-python==4.6.0.66
    - pytorch-ranger==0.1.1
    - torch-optimizer==0.1.0
    - torchinfo==1.6.3
    - torchsummaryx==1.3.0
    - torchviz==0.0.2
